### PR TITLE
add client interceptor example

### PR DESCRIPTION
**Pull request by drewwells**
switches to `go mod`, I could not get dep ensure to successfully
vendor prometheus.

### CODE REVIEW

**Review by kd7lxl — COMMENTED** [review]
Don't you need to initialize somewhere?
```go
grpc_prometheus.Register(myServer)
```
https://github.com/grpc-ecosystem/go-grpc-prometheus#server-side

**Comment by drewwells** [comment]
That sounds like the job of `atlas-toolkit`.

**Comment by kd7lxl** [comment]
> That sounds like the job of `atlas-toolkit`.

Why would you add a toolkit dependency when all the required features are in grpc-prometheus?

This is already bootstrapped completely for new apps with atlas-cli: https://github.com/infobloxopen/atlas-cli/pull/53/

**Comment by drewwells** [comment]
project is deprecated, closing

**Pull request closed without merging**
